///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DRO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DRORepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("e0b64d77-19ea-4874-bc24-f85affbc4121")]
    public partial class DRORepository : RepoGenBaseFolder
    {
        static DRORepository instance = new DRORepository();
        DRORepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        RepoItemInfo _buttonzInfo;
        RepoItemInfo _buttonyInfo;
        RepoItemInfo _buttonxInfo;

        /// <summary>
        /// Gets the singleton class instance representing the DRORepository element repository.
        /// </summary>
        [RepositoryFolder("e0b64d77-19ea-4874-bc24-f85affbc4121")]
        public static DRORepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DRORepository() 
            : base("DRORepository", "/", null, 0, false, "e0b64d77-19ea-4874-bc24-f85affbc4121", ".\\RepositoryImages\\DRORepositorye0b64d77.rximgres")
        {
            _snapxuntitled = new DRORepositoryFolders.SnapXUntitledAppFolder(this);
            _buttonzInfo = new RepoItemInfo(this, "ButtonZ", "/form[@title='Snap-X - [Untitled]']/container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1015']", 30000, null, "c55c07d6-8afc-4e32-9d9f-bddc642fd86f");
            _buttonyInfo = new RepoItemInfo(this, "ButtonY", "/form[@title='Snap-X - [Untitled]']/container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1014']", 30000, null, "37997615-3a69-4187-b785-8d3400d2de19");
            _buttonxInfo = new RepoItemInfo(this, "ButtonX", "/form[@title='Snap-X - [Untitled]']/container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1013']", 30000, null, "165dc00a-26df-41e6-beed-9240385ef914");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e0b64d77-19ea-4874-bc24-f85affbc4121")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ButtonZ item.
        /// </summary>
        [RepositoryItem("c55c07d6-8afc-4e32-9d9f-bddc642fd86f")]
        public virtual Ranorex.Button ButtonZ
        {
            get
            {
                 return _buttonzInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ButtonZ item info.
        /// </summary>
        [RepositoryItemInfo("c55c07d6-8afc-4e32-9d9f-bddc642fd86f")]
        public virtual RepoItemInfo ButtonZInfo
        {
            get
            {
                return _buttonzInfo;
            }
        }

        /// <summary>
        /// The ButtonY item.
        /// </summary>
        [RepositoryItem("37997615-3a69-4187-b785-8d3400d2de19")]
        public virtual Ranorex.Button ButtonY
        {
            get
            {
                 return _buttonyInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ButtonY item info.
        /// </summary>
        [RepositoryItemInfo("37997615-3a69-4187-b785-8d3400d2de19")]
        public virtual RepoItemInfo ButtonYInfo
        {
            get
            {
                return _buttonyInfo;
            }
        }

        /// <summary>
        /// The ButtonX item.
        /// </summary>
        [RepositoryItem("165dc00a-26df-41e6-beed-9240385ef914")]
        public virtual Ranorex.Button ButtonX
        {
            get
            {
                 return _buttonxInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ButtonX item info.
        /// </summary>
        [RepositoryItemInfo("165dc00a-26df-41e6-beed-9240385ef914")]
        public virtual RepoItemInfo ButtonXInfo
        {
            get
            {
                return _buttonxInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("5967e1e4-c72a-4711-9566-64e9242f7732")]
        public virtual DRORepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class DRORepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("5967e1e4-c72a-4711-9566-64e9242f7732")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            DRORepositoryFolders.MoveStageOptionFolder _movestageoption;
            RepoItemInfo _z_dro_valueInfo;
            RepoItemInfo _y_dro_valueInfo;
            RepoItemInfo _x_dro_valueInfo;
            InchMillimeterButtonInfoClass _inchmillimeterbuttonInfo;
            RepoItemInfo _movestagebuttonInfo;
            AxisAlignmentButtonInfoClass _axisalignmentbuttonInfo;
            CartesianPolarButtonInfoClass _cartesianpolarbuttonInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "5967e1e4-c72a-4711-9566-64e9242f7732", "")
            {
                _movestageoption = new DRORepositoryFolders.MoveStageOptionFolder(this);
                _z_dro_valueInfo = new RepoItemInfo(this, "Z_DRO_Value", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/text[@controlid='1019']", 30000, null, "28c4f339-6efa-4034-ba92-c7695fa1ef4e");
                _y_dro_valueInfo = new RepoItemInfo(this, "Y_DRO_Value", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/text[@controlid='1018']", 30000, null, "8739a128-3492-4559-b316-fb73dc535f1d");
                _x_dro_valueInfo = new RepoItemInfo(this, "X_DRO_Value", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/text[@controlid='1017']", 30000, null, "530eda37-65dc-4573-84cc-4416bbc3577e");
                _inchmillimeterbuttonInfo = new InchMillimeterButtonInfoClass(this);
                _movestagebuttonInfo = new RepoItemInfo(this, "MoveStageButton", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1668']", 30000, null, "778932f9-8b7f-4138-bae9-8c54e171819a");
                _axisalignmentbuttonInfo = new AxisAlignmentButtonInfoClass(this);
                _cartesianpolarbuttonInfo = new CartesianPolarButtonInfoClass(this);
            }

            /// <summary>
            /// The InchMillimeterButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("ebeb820f-8926-4e2b-afc6-e4e2cbeb82ba")]
            public class InchMillimeterButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// InchMillimeterButtonInfoClass class constructor.
                /// </summary>
                public InchMillimeterButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "InchMillimeterButton", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1666']", 30000, null, "ebeb820f-8926-4e2b-afc6-e4e2cbeb82ba")
                { }

                /// <summary>
                /// Gets the Screenshot_inch_mm item image.
                /// </summary>
                /// <returns>The Screenshot_inch_mm image.</returns>
                [RepositoryImage("e2a89762-f7f7-4aca-9e36-24377a303b9e")]
                public CompressedImage GetScreenshot_inch_mm()
                {
                    return GetImage("e2a89762-f7f7-4aca-9e36-24377a303b9e");
                }

                /// <summary>
                /// Gets the Screenshot_inch_mm item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e2a89762-f7f7-4aca-9e36-24377a303b9e")]
                public CompressedImage GetScreenshot_inch_mm(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e2a89762-f7f7-4aca-9e36-24377a303b9e", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot_mm_inch item image.
                /// </summary>
                /// <returns>The Screenshot_mm_inch image.</returns>
                [RepositoryImage("256795ec-3c07-4785-939f-59c984418f33")]
                public CompressedImage GetScreenshot_mm_inch()
                {
                    return GetImage("256795ec-3c07-4785-939f-59c984418f33");
                }

                /// <summary>
                /// Gets the Screenshot_mm_inch item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("256795ec-3c07-4785-939f-59c984418f33")]
                public CompressedImage GetScreenshot_mm_inch(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("256795ec-3c07-4785-939f-59c984418f33", cropRect);
                }
            }

            /// <summary>
            /// The AxisAlignmentButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("4268e7f9-23f5-49d5-896e-c8ab7d81b72f")]
            public class AxisAlignmentButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// AxisAlignmentButtonInfoClass class constructor.
                /// </summary>
                public AxisAlignmentButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "AxisAlignmentButton", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1665']", 30000, null, "4268e7f9-23f5-49d5-896e-c8ab7d81b72f")
                { }

                /// <summary>
                /// Gets the ScreenshotAxisOff item image.
                /// </summary>
                /// <returns>The ScreenshotAxisOff image.</returns>
                [RepositoryImage("d27fc3c1-5d94-45d7-8521-1b09030cfaac")]
                public CompressedImage GetScreenshotAxisOff()
                {
                    return GetImage("d27fc3c1-5d94-45d7-8521-1b09030cfaac");
                }

                /// <summary>
                /// Gets the ScreenshotAxisOff item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d27fc3c1-5d94-45d7-8521-1b09030cfaac")]
                public CompressedImage GetScreenshotAxisOff(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d27fc3c1-5d94-45d7-8521-1b09030cfaac", cropRect);
                }

                /// <summary>
                /// Gets the ScreenshotAxisOn item image.
                /// </summary>
                /// <returns>The ScreenshotAxisOn image.</returns>
                [RepositoryImage("63c6740a-033b-4281-814c-fa5b3dbeb0fd")]
                public CompressedImage GetScreenshotAxisOn()
                {
                    return GetImage("63c6740a-033b-4281-814c-fa5b3dbeb0fd");
                }

                /// <summary>
                /// Gets the ScreenshotAxisOn item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("63c6740a-033b-4281-814c-fa5b3dbeb0fd")]
                public CompressedImage GetScreenshotAxisOn(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("63c6740a-033b-4281-814c-fa5b3dbeb0fd", cropRect);
                }
            }

            /// <summary>
            /// The CartesianPolarButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("79796d2e-b982-4237-853e-f6025168c5f1")]
            public class CartesianPolarButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CartesianPolarButtonInfoClass class constructor.
                /// </summary>
                public CartesianPolarButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CartesianPolarButton", "container[@controlid='59648']/form[@title='Untitled']//container[@controlid='59649']/button[@controlid='1667']", 30000, null, "79796d2e-b982-4237-853e-f6025168c5f1")
                { }

                /// <summary>
                /// Gets the ScreenshotRA_XY item image.
                /// </summary>
                /// <returns>The ScreenshotRA_XY image.</returns>
                [RepositoryImage("4dbef803-1ebe-4288-8a07-4f8917e2e51e")]
                public CompressedImage GetScreenshotRA_XY()
                {
                    return GetImage("4dbef803-1ebe-4288-8a07-4f8917e2e51e");
                }

                /// <summary>
                /// Gets the ScreenshotRA_XY item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4dbef803-1ebe-4288-8a07-4f8917e2e51e")]
                public CompressedImage GetScreenshotRA_XY(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4dbef803-1ebe-4288-8a07-4f8917e2e51e", cropRect);
                }

                /// <summary>
                /// Gets the ScreenshotXY_RA item image.
                /// </summary>
                /// <returns>The ScreenshotXY_RA image.</returns>
                [RepositoryImage("a15afeb8-7c27-49fe-a8a6-20533940dba9")]
                public CompressedImage GetScreenshotXY_RA()
                {
                    return GetImage("a15afeb8-7c27-49fe-a8a6-20533940dba9");
                }

                /// <summary>
                /// Gets the ScreenshotXY_RA item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a15afeb8-7c27-49fe-a8a6-20533940dba9")]
                public CompressedImage GetScreenshotXY_RA(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a15afeb8-7c27-49fe-a8a6-20533940dba9", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5967e1e4-c72a-4711-9566-64e9242f7732")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5967e1e4-c72a-4711-9566-64e9242f7732")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Z_DRO_Value item.
            /// </summary>
            [RepositoryItem("28c4f339-6efa-4034-ba92-c7695fa1ef4e")]
            public virtual Ranorex.Text Z_DRO_Value
            {
                get
                {
                    return _z_dro_valueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Z_DRO_Value item info.
            /// </summary>
            [RepositoryItemInfo("28c4f339-6efa-4034-ba92-c7695fa1ef4e")]
            public virtual RepoItemInfo Z_DRO_ValueInfo
            {
                get
                {
                    return _z_dro_valueInfo;
                }
            }

            /// <summary>
            /// The Y_DRO_Value item.
            /// </summary>
            [RepositoryItem("8739a128-3492-4559-b316-fb73dc535f1d")]
            public virtual Ranorex.Text Y_DRO_Value
            {
                get
                {
                    return _y_dro_valueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Y_DRO_Value item info.
            /// </summary>
            [RepositoryItemInfo("8739a128-3492-4559-b316-fb73dc535f1d")]
            public virtual RepoItemInfo Y_DRO_ValueInfo
            {
                get
                {
                    return _y_dro_valueInfo;
                }
            }

            /// <summary>
            /// The X_DRO_Value item.
            /// </summary>
            [RepositoryItem("530eda37-65dc-4573-84cc-4416bbc3577e")]
            public virtual Ranorex.Text X_DRO_Value
            {
                get
                {
                    return _x_dro_valueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The X_DRO_Value item info.
            /// </summary>
            [RepositoryItemInfo("530eda37-65dc-4573-84cc-4416bbc3577e")]
            public virtual RepoItemInfo X_DRO_ValueInfo
            {
                get
                {
                    return _x_dro_valueInfo;
                }
            }

            /// <summary>
            /// The InchMillimeterButton item.
            /// </summary>
            [RepositoryItem("ebeb820f-8926-4e2b-afc6-e4e2cbeb82ba")]
            public virtual Ranorex.Button InchMillimeterButton
            {
                get
                {
                    return _inchmillimeterbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The InchMillimeterButton item info.
            /// </summary>
            [RepositoryItemInfo("ebeb820f-8926-4e2b-afc6-e4e2cbeb82ba")]
            public virtual InchMillimeterButtonInfoClass InchMillimeterButtonInfo
            {
                get
                {
                    return _inchmillimeterbuttonInfo;
                }
            }

            /// <summary>
            /// The MoveStageButton item.
            /// </summary>
            [RepositoryItem("778932f9-8b7f-4138-bae9-8c54e171819a")]
            public virtual Ranorex.Button MoveStageButton
            {
                get
                {
                    return _movestagebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MoveStageButton item info.
            /// </summary>
            [RepositoryItemInfo("778932f9-8b7f-4138-bae9-8c54e171819a")]
            public virtual RepoItemInfo MoveStageButtonInfo
            {
                get
                {
                    return _movestagebuttonInfo;
                }
            }

            /// <summary>
            /// The AxisAlignmentButton item.
            /// </summary>
            [RepositoryItem("4268e7f9-23f5-49d5-896e-c8ab7d81b72f")]
            public virtual Ranorex.Button AxisAlignmentButton
            {
                get
                {
                    return _axisalignmentbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AxisAlignmentButton item info.
            /// </summary>
            [RepositoryItemInfo("4268e7f9-23f5-49d5-896e-c8ab7d81b72f")]
            public virtual AxisAlignmentButtonInfoClass AxisAlignmentButtonInfo
            {
                get
                {
                    return _axisalignmentbuttonInfo;
                }
            }

            /// <summary>
            /// The CartesianPolarButton item.
            /// </summary>
            [RepositoryItem("79796d2e-b982-4237-853e-f6025168c5f1")]
            public virtual Ranorex.Button CartesianPolarButton
            {
                get
                {
                    return _cartesianpolarbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CartesianPolarButton item info.
            /// </summary>
            [RepositoryItemInfo("79796d2e-b982-4237-853e-f6025168c5f1")]
            public virtual CartesianPolarButtonInfoClass CartesianPolarButtonInfo
            {
                get
                {
                    return _cartesianpolarbuttonInfo;
                }
            }

            /// <summary>
            /// The MoveStageOption folder.
            /// </summary>
            [RepositoryFolder("610a540c-1bf4-46e6-ac34-9a1c565c4cc2")]
            public virtual DRORepositoryFolders.MoveStageOptionFolder MoveStageOption
            {
                get { return _movestageoption; }
            }
        }

        /// <summary>
        /// The MoveStageOptionFolder folder.
        /// </summary>
        [RepositoryFolder("610a540c-1bf4-46e6-ac34-9a1c565c4cc2")]
        public partial class MoveStageOptionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttongotoInfo;
            RepoItemInfo _x_valueInfo;
            RepoItemInfo _y_valueInfo;
            RepoItemInfo _buttoncloseInfo;

            /// <summary>
            /// Creates a new MoveStageOption  folder.
            /// </summary>
            public MoveStageOptionFolder(RepoGenBaseFolder parentFolder) :
                    base("MoveStageOption", "container[@controlid='59648']/form[@title='Untitled']//element[@controlid='59664']/container[@controlid='59648']", parentFolder, 30000, null, false, "610a540c-1bf4-46e6-ac34-9a1c565c4cc2", "")
            {
                _buttongotoInfo = new RepoItemInfo(this, "ButtonGoTo", "button[@text='&Go To']", 30000, null, "456f7989-d900-4487-b1ee-ac1bca7daa0b");
                _x_valueInfo = new RepoItemInfo(this, "X_Value", "text[@controlid='2362']", 30000, null, "3ded1822-ca7b-45c2-86bc-18acc63cfa7a");
                _y_valueInfo = new RepoItemInfo(this, "Y_Value", "text[@controlid='2363']", 30000, null, "5204792c-8fd1-46ac-bc0b-d3ff4d5bde23");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "button[@text='&Close']", 30000, null, "6c32911a-9c5a-4cf3-b6e4-c04f4e3c3098");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("610a540c-1bf4-46e6-ac34-9a1c565c4cc2")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("610a540c-1bf4-46e6-ac34-9a1c565c4cc2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonGoTo item.
            /// </summary>
            [RepositoryItem("456f7989-d900-4487-b1ee-ac1bca7daa0b")]
            public virtual Ranorex.Button ButtonGoTo
            {
                get
                {
                    return _buttongotoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonGoTo item info.
            /// </summary>
            [RepositoryItemInfo("456f7989-d900-4487-b1ee-ac1bca7daa0b")]
            public virtual RepoItemInfo ButtonGoToInfo
            {
                get
                {
                    return _buttongotoInfo;
                }
            }

            /// <summary>
            /// The X_Value item.
            /// </summary>
            [RepositoryItem("3ded1822-ca7b-45c2-86bc-18acc63cfa7a")]
            public virtual Ranorex.Text X_Value
            {
                get
                {
                    return _x_valueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The X_Value item info.
            /// </summary>
            [RepositoryItemInfo("3ded1822-ca7b-45c2-86bc-18acc63cfa7a")]
            public virtual RepoItemInfo X_ValueInfo
            {
                get
                {
                    return _x_valueInfo;
                }
            }

            /// <summary>
            /// The Y_Value item.
            /// </summary>
            [RepositoryItem("5204792c-8fd1-46ac-bc0b-d3ff4d5bde23")]
            public virtual Ranorex.Text Y_Value
            {
                get
                {
                    return _y_valueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Y_Value item info.
            /// </summary>
            [RepositoryItemInfo("5204792c-8fd1-46ac-bc0b-d3ff4d5bde23")]
            public virtual RepoItemInfo Y_ValueInfo
            {
                get
                {
                    return _y_valueInfo;
                }
            }

            /// <summary>
            /// The ButtonClose item.
            /// </summary>
            [RepositoryItem("6c32911a-9c5a-4cf3-b6e4-c04f4e3c3098")]
            public virtual Ranorex.Button ButtonClose
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonClose item info.
            /// </summary>
            [RepositoryItemInfo("6c32911a-9c5a-4cf3-b6e4-c04f4e3c3098")]
            public virtual RepoItemInfo ButtonCloseInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}